repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.5
    hooks:
      - id: uv-export
        name: uv-export requirements.txt
        args: [--quiet, --no-dev, --output-file, requirements.txt]
      - id: uv-export
        name: uv-export requirements-dev.txt
        args: [--quiet, --only-dev, --output-file, requirements-dev.txt]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.11.0-1
    hooks:
      - id: shfmt
        args: [--indent, "4", --write]

  - repo: https://github.com/openstack/bashate
    rev: 2.1.1
    hooks:
      - id: bashate
        args: [--verbose, --ignore=E006]

  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.38.0
    hooks:
      - id: check-compose-spec
      - id: check-jsonschema
        name: Validate toolinfo.json
        files: (^|/)toolinfo\.json$
        args:
          - --schemafile
          - https://raw.githubusercontent.com/wikimedia/wikimedia-toolhub/main/jsonschema/toolinfo/1.2.2.json

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.28.0
    hooks:
      - id: pyproject-fmt
