version: '2'
services:
  web:
    build:
      context: .
      dockerfile: conf/Dockerfile.web
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=integraality/app.py
      - FLASK_ENV=development
      - PYWIKIBOT_NO_USER_CONFIG=1
      - PYTHONPATH=/code/integraality/
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    ports:
      - 5000:5000
    volumes:
      - .:/code
    depends_on:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
