services:
  web:
    build:
      context: .
      dockerfile: conf/Dockerfile.web
      network: host
    command: flask run --host=0.0.0.0 --debug
    env_file:
      - dev.env
    environment:
      - FLASK_APP=integraality.app
      - PYWIKIBOT_NO_USER_CONFIG=1
      - REDIS_HOST=redis
      - LOCAL_WRITE_PATH=docker_pages
    ports:
     - 5000:5000
    volumes:
     - .:/code
    depends_on:
     - redis
     - db

  redis:
    image: redis:3.2.6
    ports:
     - 6379:6379

  db:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
     - 3306:3306
