[project]
name = "integraality"
version = "0.0.1"
requires-python = "~=3.11.0"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
]
dependencies = [
  "flask",
  "mwparserfromhell",
  "pywikibot",
  "redis",
]

[dependency-groups]
dev = [
  "fakeredis",
  "pytest",
  "pytest-cov",
]

[tool.uv]
package = false

[tool.ruff]
lint.extend-select = [ "I" ]
