---
- hosts: toolforge
  gather_facts: no

  vars:
    tool_name: integraality
    base_path: "/data/project/{{ tool_name }}"
    logs_path: "{{ base_path }}/logs"
    checkout_path: "{{ base_path }}/integraality"
    toolforge_path: "{{ base_path }}/www/python"
    virtualenv_path: "{{ toolforge_path }}/venv"
    source_path: "{{ toolforge_path }}/src"

  handlers:
    - name: Restart webservice
      command: >
        webservice restart

    - name: Display message
      debug:
        msg: >
          Deploy done. Please update the Server Admin Log via IRC:
          https://webchat.freenode.net/?channels=#wikimedia-labs

  tasks:
    - name: Ensure directories exist
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ logs_path }}"
        - "{{ toolforge_path }}"
      tags:
        - paths

    - name: Clone Git repository
      git:
        repo: 'https://github.com/JeanFred/integraality'
        dest: '{{ checkout_path }}'
      notify:
        - Restart webservice
        - Display message
      tags:
        - git
        - skip_ansible_lint  # Skip E401, we always want latest version

    # - name: Install requirements
    #   pip:
    #     requirements: '{{ checkout_path }}/requirements.txt'
    #     virtualenv: '{{ virtualenv_path }}'
    #   tags:
    #     - requirements

    - name: Deploy uwsgi configuration file
      template:
        src: 'uwsgi.ini.j2'
        dest: '{{ toolforge_path }}/uwsgi.ini'
      tags:
        - config

    - name: Symlink src directory
      file:
        src: '{{ checkout_path }}/integraality/'
        path: '{{ source_path }}'
        state: link
      tags:
        - paths

    - name: Cron environment variables
      cron:
        name: "{{ item.name }}"
        env: yes
        value: "{{ item.value }}"
      with_items:
        - {name: 'UPDATE_SCRIPT', value: "{{ checkout_path }}/bin/run.sh"}
        - {name: 'UPDATE_LOG_FILE_META', value: "{{ logs_path }}/daily-update-meta.log"}
        - {name: 'UPDATE_LOG_FILE_WIKIDATA', value: "{{ logs_path }}/weekly-update-wikidata.log"}
        - {name: 'CRONTAB_LOG_FILE', value: "{{ logs_path }}/crontab.log"}
        - {name: 'JSUB_PARAMS', value: '-mem 1000m -once -j y'}
      tags:
        - crontab

    - name: Weekly job updating all dashboards on Wikidata
      cron:
        name: Weekly update
        special_time: weekly
        job: jsub $JSUB_PARAMS -o $UPDATE_LOG_FILE_WIKIDATA -N weekly-update $UPDATE_SCRIPT wikidata >> $CRONTAB_LOG_FILE
      tags:
        - crontab

    - name: Daily job updating all dashboards on Meta
      cron:
        name: Daily Meta update
        special_time: daily
        job: jsub $JSUB_PARAMS -o $UPDATE_LOG_FILE_META -N daily-update-meta $UPDATE_SCRIPT meta https://meta.wikimedia.org/wiki/ >> $CRONTAB_LOG_FILE
      tags:
        - crontab
