---
- hosts: toolforge
  gather_facts: no

  vars:
    tool_name: integraality
    base_path: "/data/project/{{ tool_name }}"
    logs_path: "{{ base_path }}/logs"
    checkout_path: "{{ base_path }}/integraality"
    toolforge_path: "{{ base_path }}/www/python"
    virtualenv_path: "{{ toolforge_path }}/venv"
    source_path: "{{ toolforge_path }}/src"
    jobs_file_path: "{{ base_path }}/jobs.yml"

    jobs:
      - name: weekly-update-wikidata
        command: "{{ checkout_path }}/bin/run.sh wikidata"
        image: python3.9
        schedule: "@weekly"
        emails: all
        mem: 1G
        filelog-stdout: logs/weekly-update-wikidata-out.log
        filelog-stderr: logs/weekly-update-wikidata-err.log

  handlers:
    - name: Restart webservice
      command: >
        webservice restart

    - name: Display message
      debug:
        msg: >
          Deploy done. Please update the Server Admin Log via IRC:
          https://webchat.freenode.net/?channels=#wikimedia-labs

    - name: Load Toolforge jobs from file
      command: >
        toolforge jobs load {{ jobs_file_path }}

  tasks:
    - name: Ensure directories exist
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ logs_path }}"
        - "{{ toolforge_path }}"
      tags:
        - paths

    - name: Clone Git repository
      git:
        repo: 'https://github.com/JeanFred/integraality'
        dest: '{{ checkout_path }}'
      notify:
        - Restart webservice
        - Display message
      tags:
        - git
        - skip_ansible_lint  # Skip E401, we always want latest version

    # - name: Install requirements
    #   pip:
    #     requirements: '{{ checkout_path }}/requirements.txt'
    #     virtualenv: '{{ virtualenv_path }}'
    #   tags:
    #     - requirements

    - name: Deploy uwsgi configuration file
      template:
        src: 'uwsgi.ini.j2'
        dest: '{{ toolforge_path }}/uwsgi.ini'
      tags:
        - config

    - name: Symlink src directory
      file:
        src: '{{ checkout_path }}/integraality/'
        path: '{{ source_path }}'
        state: link
      tags:
        - paths

    - name: Weekly job updating all dashboards on Wikidata
      ansible.builtin.copy:
        content: '{{ jobs | to_nice_yaml(sort_keys=false) }}'
        dest: '{{ jobs_file_path }}'
      notify:
        - Load Toolforge jobs from file
      tags:
        - jobs
